export const categories: App.Category[] = [
    { name: "Skip", icon: "fast-forward" },
    {
        name: "Entertainment & Sports",
        icon: "clapperboard",
        subcategories: [
            { name: "News & Current Events", icon: "newspaper" },
            { name: "Memes & Media", icon: "laugh" },
            { name: "Music", icon: "music" },
            { name: "TV & Films", icon: "tv" },
            { name: "Books & Writing", icon: "library-big" },
            { name: "Art", icon: "image" },
            { name: "Gaming", icon: "gamepad" },
            { name: "Sports", icon: "medal" },
            { name: "Gambling", icon: "dices" },
            { name: "NSFW", icon: "eye-off" },
        ],
    },
    {
        name: "Hobbies",
        icon: "gamepad",
        subcategories: [
            { name: "Music", icon: "music" },
            { name: "Arts & Crafts", icon: "image" },
            { name: "Sports", icon: "medal" },
            { name: "Outdoors", icon: "tent-tree" },
            { name: "Photography & Videography", icon: "camera" },
            { name: "Machines & Transportation", icon: "car" },
            { name: "Recreational Drugs", icon: "pill" },
        ],
    },
    {
        name: "Finance",
        icon: "circle-dollar-sign",
        subcategories: [
            { name: "Macro & Economics", icon: "globe-2" },
            { name: "Personal Finance", icon: "wallet" },
            { name: "Investing", icon: "line-chart" },
            { name: "Bitcoin", icon: "bitcoin" },
            { name: "Altcoins", icon: "trash-2" },
        ],
    },
    {
        name: "Science & Technology",
        icon: "cpu",
        subcategories: [
            { name: "Nostr", icon: "network" },
            { name: "Internet Technology", icon: "globe" },
            { name: "Energy Technology", icon: "atom" },
            { name: "Transportation Technology", icon: "plane" },
            { name: "Medical Technology", icon: "activity-square" },
            { name: "Formal Sciences", icon: "sigma-square" },
            { name: "Natural Sciences", icon: "flask-conical" },
            { name: "Social Sciences", icon: "person-standing" },
        ],
    },
    {
        name: "Philosophy, Religion, Law, & History",
        icon: "graduation-cap",
        subcategories: [
            { name: "Philosophy", icon: "sparkle" },
            { name: "Religion", icon: "church" },
            { name: "Law", icon: "gavel" },
            { name: "History", icon: "book-open-text" },
        ],
    },
    {
        name: "Health & Wellness",
        icon: "heart-pulse",
        subcategories: [
            { name: "Conventional Medicine", icon: "syringe" },
            { name: "Alternative Medicine", icon: "salad" },
            { name: "Yoga & Meditation", icon: "sparkles" },
            { name: "Exercise", icon: "dumbbell" },
            { name: "Mental Health", icon: "brain" },
        ],
    },
    {
        name: "Food & Drink",
        icon: "utensils",
        subcategories: [
            { name: "Food", icon: "beef" },
            { name: "Cooking", icon: "chef-hat" },
            { name: "Recipes", icon: "book-marked" },
            { name: "Drinks & Mixology", icon: "martini" },
        ],
    },
    {
        name: "Travel",
        icon: "map-pinned",
        subcategories: [
            { name: "Destinations", icon: "map-pinned" },
            { name: "Tips & Tricks", icon: "sparkles" },
        ],
    },
];
